name: My Workflow

on:
  # Runs when manually triggered
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: 24f1000322@ds.study.iitm.ac.in
        run: echo "Hello, world!"
